# Generated by Django 3.2.18 on 2026-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halftone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halftonejob',
            name='blur',
            field=models.FloatField(default=0.0, verbose_name='Desenfoque (px)'),
        ),
        migrations.AddField(
            model_name='halftonejob',
            name='brightness',
            field=models.FloatField(default=0.0, verbose_name='Brillo'),
        ),
        migrations.AddField(
            model_name='halftonejob',
            name='gamma',
            field=models.FloatField(default=1.0, verbose_name='Gamma'),
        ),
        migrations.AddField(
            model_name='halftonejob',
            name='gradient_intensity',
            field=models.FloatField(default=0.8, verbose_name='Intensidad de gradiente'),
        ),
        migrations.AlterField(
            model_name='halftonejob',
            name='contrast_boost',
            field=models.FloatField(default=1.2, verbose_name='Contraste'),
        ),
        migrations.AlterField(
            model_name='halftonejob',
            name='dot_size',
            field=models.FloatField(default=6.0, verbose_name='Tamaño del punto (px)'),
        ),
    ]
