# Generated by Django 3.2.18 on 2024-09-13 03:57

from django.conf import settings
import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditlog', '0012_add_logentry_action_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='Fecha Evento')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Log Respaldo Base de Datos',
                'verbose_name_plural': 'Logs Respaldos Base de Datos',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
            ],
            options={
                'verbose_name': 'Log de Usuario',
                'verbose_name_plural': 'Logs de Administración',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
            ],
            options={
                'verbose_name': 'Log de Usuario',
                'verbose_name_plural': 'Logs de Sistema',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('remote_address', models.CharField(max_length=100)),
                ('server_hostname', models.CharField(max_length=200)),
                ('domain_url', models.CharField(max_length=200)),
                ('request_method', models.CharField(max_length=100)),
                ('request_path', models.TextField()),
                ('request_body', models.TextField(blank=True, null=True)),
                ('run_time', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_module_requestlog_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_module_requestlog_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Log de Solicitud',
                'verbose_name_plural': 'Logs de Solicitudes',
            },
        ),
    ]
