# Generated by Django 3.2.18 on 2024-09-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transversal', '0002_auto_20240917_1500'),
        ('multi_tenant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotivoNotificacion',
        ),
        migrations.DeleteModel(
            name='TipoNotificacion',
        ),
    ]
