# Generated by Django 3.2.18 on 2024-09-13 03:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import helpers.classes.storage
import helpers.functions.utils
import helpers.functions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multi_tenant', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTemplateDinamico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria Template Dinamico',
                'verbose_name_plural': 'Categorias Template Dinamico',
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Model Config',
                'verbose_name_plural': 'Models Configs',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('contexto', models.TextField(blank=True)),
                ('otros_destinos', models.TextField(blank=True, help_text='Destinos de email que no son parte del sistema.', null=True, verbose_name='Otros Destinatarios')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('send_notification_sms', models.BooleanField(default=False, verbose_name='¿Paciente permite envio de notificacion sms?')),
                ('send_notification_wsp', models.BooleanField(default=False, verbose_name='¿Paciente permite envio de notificacion whatsapp?')),
                ('adjunto', models.FileField(blank=True, max_length=500, null=True, upload_to='adjuntos/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension], verbose_name='Adjunto')),
                ('adjunto_list', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(max_length=200, upload_to='adjuntos/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension]), blank=True, null=True, size=None)),
                ('delete_adjunto', models.BooleanField(default=True, verbose_name='¿Borrar lista de archivos adjuntos?')),
                ('delete_from_full_url_attach', models.BooleanField(default=True, verbose_name='¿Borrar lista desde full url archivos adjuntos?')),
                ('error_messages_attach_files', models.TextField(blank=True, default='', verbose_name='Mensajes de error durante el procesamiento de archivos adjuntos')),
                ('es_leido', models.BooleanField(default=False, verbose_name='¿Está leída?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destinos', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Destinatarios')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones | Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificacionMailConfigProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('es_activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('is_principal', models.BooleanField(default=False, verbose_name='¿Es principal?')),
                ('integracion', models.IntegerField(choices=[(1, 'POP3'), (2, 'SMTP')], verbose_name='Integración')),
            ],
            options={
                'verbose_name': 'Provider Email',
                'verbose_name_plural': 'Notificaciones | Provider Email',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, help_text='Icono por defecto ara esta notificacion', null=True, upload_to='notificaciones/icons/%Y/%m/%d', verbose_name='Icono')),
                ('imagen', models.FileField(blank=True, help_text='Imagen por defecto para esta notificacion. (Solo para Chrome, Firefox y Android)', null=True, upload_to='notificaciones/images/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension_img], verbose_name='Imagen')),
                ('badge', models.FileField(blank=True, help_text='Badge por defecto para esta notificacion. (Solo para Chrome y Android)', null=True, upload_to='notificaciones/badges/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension_img], verbose_name='Badge')),
                ('url_trigger', models.CharField(blank=True, help_text='Url.', max_length=200, null=True)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'Alta'), (2, 'Normal')], null=True)),
                ('hash_provider', models.CharField(blank=True, help_text='id de proveedor.', max_length=255, null=True)),
                ('es_enviada', models.BooleanField(default=False, verbose_name='¿Está Enviada?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notificacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_messages', to='transversal.notificacion')),
            ],
            options={
                'verbose_name': 'Notificación Push',
                'verbose_name_plural': 'Notificaciones | Notificaciones Push',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPushConfigProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('es_activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('integracion', models.IntegerField(choices=[(1, 'Onesignal'), (2, 'Google Firebase')], verbose_name='Integración')),
            ],
            options={
                'verbose_name': 'Provider Push',
                'verbose_name_plural': 'Notificaciones | Provider Push',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPushDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Notificaciones | Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='NotificacionSmsConfigProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('es_activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
            ],
            options={
                'verbose_name': 'Provider SMS/WHATSAPP',
                'verbose_name_plural': 'Notificaciones | Provider SMS/WHATSAPP',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('parameter_type', models.IntegerField(choices=[(1, 'Texto Libre'), (2, 'Selección')], default=1, verbose_name='Tipo')),
                ('parameter_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('description', models.TextField(default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SmsServiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=100, verbose_name='Respuesta')),
                ('response_type', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], null=True, verbose_name='Tipo de Respuesta')),
            ],
            options={
                'verbose_name': 'Registro de respuesta | Mensajeria SMS/WHATSAPP',
                'verbose_name_plural': 'Registros de respuestas | Mensajeria SMS/WHATSAPP',
            },
        ),
        migrations.CreateModel(
            name='TemplateDocumentoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('documento', models.IntegerField(choices=[(2, 'Item de Liquidación'), (1, 'Liquidación')], null=True)),
                ('template', models.FileField(max_length=200, storage=helpers.classes.storage.LocalMediaStorage(), upload_to='template/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension_odt], verbose_name='Plantilla')),
                ('formato', models.IntegerField(choices=[(1, 'Word'), (2, 'PDF')], default=2)),
                ('tags_available', models.JSONField(blank=True, null=True, verbose_name='Tags disponibles')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento Fijo',
                'verbose_name_plural': 'Plantillas de Documentos Fijos',
            },
        ),
        migrations.CreateModel(
            name='TemplateNotificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null='True')),
                ('motivo_notificacion', models.IntegerField(choices=[(1, 'Credenciales de Acceso'), (2, 'Autenticación Doble Factor'), (3, 'Envio de Liquidación a Profesional')], null=True, verbose_name='Motivo')),
                ('plantilla', models.FileField(blank=True, max_length=200, null=True, storage=helpers.classes.storage.LocalMediaStorage(), upload_to='template/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension_odt], verbose_name='Plantilla')),
                ('html', models.TextField(help_text='HTML El cuerpo del correo.')),
                ('text_body_sms', models.TextField(blank=True, help_text='Texto del mensaje SMS (No puede ser mayor a 120 caracteres).', max_length=160, null=True, verbose_name='Texto mensaje SMS')),
                ('text_body_wsp', models.TextField(blank=True, help_text='Texto del mensaje Whatsapp', null=True, verbose_name='Texto mensaje Whatsapp')),
                ('receive_reply', models.BooleanField(default=False, verbose_name='¿Recibe respuesta del usuario(SMS/Whatsapp)')),
                ('icono', models.FileField(blank=True, null=True, upload_to='template_notifications_icon', validators=[helpers.functions.validators.validate_file_extension_img], verbose_name='Icono')),
                ('generate_ics_file', models.BooleanField(default=False, verbose_name='¿Permite enviar archivo.ics para conectar datos de paciente con Google Calendar?')),
                ('destinos', models.ManyToManyField(blank=True, related_name='user_destinatarios', to=settings.AUTH_USER_MODEL)),
                ('mail_provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionmailconfigprovider', verbose_name='Email Provider')),
                ('push_provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionpushconfigprovider', verbose_name='Push Provider')),
                ('sms_provider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionsmsconfigprovider', verbose_name='SMS/WHATSAPP Provider')),
                ('tipo_notificacion', models.ManyToManyField(to='multi_tenant.TipoNotificacion', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Notificaciones | Templates',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contenttypes.contenttype',),
        ),
        migrations.CreateModel(
            name='UserTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multi_tenant.tour')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour de Usuario',
                'verbose_name_plural': 'Tours de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='TemplateNotificacionParametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('priority', 'PRIORITY'), ('icon', 'ICON'), ('image', 'IMAGE'), ('badge', 'BADGE'), ('url', 'URL'), ('message', 'MESSAGE')], max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.templatenotificacion')),
            ],
            options={
                'verbose_name': 'Parámetro de Template',
                'verbose_name_plural': 'Notificaciones | Parámetros de Template',
            },
        ),
        migrations.CreateModel(
            name='TemplateDocumentoDinamico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('template', models.FileField(storage=helpers.classes.storage.LocalMediaStorage(), upload_to='template/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension_odt], verbose_name='Plantilla')),
                ('formato', models.IntegerField(choices=[(1, 'Word'), (2, 'PDF')], default=2)),
                ('app', models.CharField(blank=True, choices=[('admin_auto_filters', 'admin_auto_filters'), ('drf_spectacular', 'drf_spectacular'), ('drf_spectacular_sidecar', 'drf_spectacular_sidecar'), ('auditlog', 'auditlog'), ('pwa', 'pwa'), ('app.audit_module', 'app.audit_module'), ('app.transversal', 'app.transversal'), ('app.theme', 'app.theme'), ('app.medical_fees', 'app.medical_fees'), ('two_factor', 'two_factor')], max_length=250, null=True)),
                ('model', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transversal.categoriatemplatedinamico', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento Dinámico',
                'verbose_name_plural': 'Plantillas de Documentos Dinámicos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_auth', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_push', models.CharField(blank=True, max_length=200, null=True)),
                ('run', models.CharField(blank=True, max_length=13, null=True, validators=[helpers.functions.utils.valid_run], verbose_name='R.U.N.')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('es', 'Español')], default='es-ES', max_length=50, verbose_name='Idioma')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reset_password', models.BooleanField(default=False, help_text='Si está marcado se reseteará la contraseña y la enviará al email del usuario.', verbose_name='¿Resetear contraseña y enviar por email?')),
                ('tour', models.BooleanField(default=False, verbose_name='¿Forzar Tour?')),
                ('access_only_for_api', models.BooleanField(default=False, help_text='Solo tendra acceso a las APIS del sistema, NO podra iniciar sesión de manera normal', verbose_name='Acceso solo a APIS')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='NotificacionSmsConfigProviderParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('ACCOUNT_SID', 'ACCOUNT_SID'), ('AUTH_TOKEN', 'AUTH_TOKEN'), ('PHONE_NUMBER', 'PHONE_NUMBER'), ('PHONE_NUMBER_WHATSAPP', 'PHONE_NUMBER_WHATSAPP')], max_length=250)),
                ('valor', models.CharField(max_length=250)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionsmsconfigprovider')),
            ],
            options={
                'verbose_name': 'Parámetro SMS/WHATSAPP',
                'verbose_name_plural': 'Notificaciones | Parámetros SMS/WHATSAPP',
            },
        ),
        migrations.CreateModel(
            name='NotificacionSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0, verbose_name='Costo de operación')),
                ('cost_unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidad de costo')),
                ('es_enviada', models.BooleanField(default=False)),
                ('notification_type', models.IntegerField(choices=[(1, 'SMS'), (2, 'WHATSAPP')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notificacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='transversal.notificacion')),
            ],
            options={
                'verbose_name': 'Notificación SMS/WHATSAPP',
                'verbose_name_plural': 'Notificaciones | Notificaciones SMS/WHATSAPP',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPushEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'CREADA'), (1, 'ENVIADA'), (2, 'LEIDA'), (3, 'ERROR')])),
                ('response', models.TextField(blank=True, help_text='Respuesta del proveedor de mensajeria.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionpush')),
            ],
            options={
                'verbose_name': 'Log de Notificación Push',
                'verbose_name_plural': 'Notificaciones | Logs de Notificaciones Push',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPushDevicesParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=250, null=True)),
                ('valor', models.CharField(blank=True, max_length=250, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='transversal.notificacionpushdevices')),
            ],
            options={
                'verbose_name': 'Info de Dispositivo',
                'verbose_name_plural': 'Notificaciones | Info de Dispositivos',
            },
        ),
        migrations.AddField(
            model_name='notificacionpushdevices',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.perfil'),
        ),
        migrations.CreateModel(
            name='NotificacionPushConfigProviderParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('app_id', 'APP_ID'), ('rest_auth', 'REST_AUTH'), ('url', 'URL')], max_length=250)),
                ('valor', models.CharField(max_length=250)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionpushconfigprovider')),
            ],
            options={
                'verbose_name': 'Parámetro Push',
                'verbose_name_plural': 'Notificaciones | Parámetros Push',
            },
        ),
        migrations.AddField(
            model_name='notificacionpush',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionpushconfigprovider'),
        ),
        migrations.CreateModel(
            name='NotificacionMailConfigProviderParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('EMAIL_HOST', 'EMAIL_HOST'), ('EMAIL_PORT', 'EMAIL_PORT'), ('EMAIL_HOST_USER', 'EMAIL_HOST_USER'), ('EMAIL_HOST_PASSWORD', 'EMAIL_HOST_PASSWORD'), ('DEFAULT_FROM_EMAIL', 'DEFAULT_FROM_EMAIL'), ('SERVER_EMAIL', 'SERVER_EMAIL'), ('EMAIL_SUBJECT_PREFIX', 'EMAIL_SUBJECT_PREFIX'), ('EMAIL_USE_TLS', 'EMAIL_USE_TLS'), ('EMAIL_USE_SSL', 'EMAIL_USE_SSL')], max_length=250)),
                ('valor', models.CharField(max_length=250)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.notificacionmailconfigprovider')),
            ],
            options={
                'verbose_name': 'Parámetro Email',
                'verbose_name_plural': 'Notificaciones | Parámetros Email',
            },
        ),
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, max_length=200, null=True)),
                ('es_enviada', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notificacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='transversal.notificacion')),
            ],
            options={
                'verbose_name': 'Notificación Email',
                'verbose_name_plural': 'Notificaciones | Notificaciones Email',
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.templatenotificacion'),
        ),
        migrations.CreateModel(
            name='ModelFieldConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='field')),
                ('required', models.BooleanField(default=False, verbose_name='is required?')),
                ('visible', models.BooleanField(default=True, verbose_name='is visible?')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.modelconfig', verbose_name='Configuracion de campos')),
            ],
            options={
                'verbose_name': 'Model Field Config',
                'verbose_name_plural': 'Model Field Configs',
            },
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.contenttype', verbose_name='Configuracion de modelo'),
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('external_id', models.BigIntegerField(verbose_name='ID Sistema Externo')),
                ('identification', models.CharField(default='', max_length=25, verbose_name='Identificación')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_insurer_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_insurer_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='FileTemplateNotificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=helpers.classes.storage.LocalMediaStorage(), upload_to='files_template/%Y/%m/%d', validators=[helpers.functions.validators.validate_file_extension_odt])),
                ('format_file', models.IntegerField(choices=[(1, 'Word'), (2, 'PDF')], default=0, help_text='Es el formato en el que se envia el archivo.', verbose_name='Formato')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.templatenotificacion')),
            ],
            options={
                'verbose_name': 'Archivos de Template de Notificación',
                'verbose_name_plural': 'Notificaciones | Archivos de Template',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('type', models.IntegerField(choices=[(1, 'Login'), (2, 'Consultas Ambulatorias'), (3, 'Exámenes'), (4, 'Tratamientos Ambulatorios'), (5, 'Cirugías'), (6, 'Maestro de Usuarios'), (7, 'Maestro de Especialidades'), (8, 'Maestro de Profesionales'), (9, 'Maestro de Sociedad de Profesionales'), (10, 'Maestro de Aseguradoras')], null=True, verbose_name='Tipo')),
                ('integration_type', models.IntegerField(choices=[(1, 'Rest')], default=1, null=True, verbose_name='Tipo de Integración')),
                ('authentication_type', models.IntegerField(choices=[(1, 'JWT')], default=1, null=True, verbose_name='Tipo de Autenticación')),
                ('authentication_type_jwt', models.IntegerField(blank=True, choices=[(1, 'Token Login'), (2, 'Token Refresh'), (3, 'Token Verify')], null=True, verbose_name='Tipo de Endpoint JWT')),
                ('authorization_header_prefix', models.CharField(blank=True, default='', help_text='Ejemplo: Bearer, Basic, Digest o Alguno Propio', max_length=200, verbose_name='Prefijo Header Authorization')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('url', models.URLField(null=True, verbose_name='URL')),
                ('method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], null=True, verbose_name='Tipo de Método')),
                ('query_params', models.TextField(blank=True, help_text='Query params que van en la url del endpoint', verbose_name='Parametros Query')),
                ('body', models.TextField(blank=True, help_text='Utilizado para envio de datos en método POST', verbose_name='Datos del Cuerpo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_endpoint_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_endpoint_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Configurador de Endpoints',
            },
        ),
    ]
