# Generated by Django 3.2.18 on 2024-09-17 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transversal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('subject', models.CharField(max_length=200)),
                ('context', models.TextField(blank=True)),
                ('destination', models.TextField(blank=True, null=True, verbose_name='Destinatarios')),
                ('is_read', models.BooleanField(default=False, verbose_name='¿Está leída?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_notification_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_notification_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones | Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha modificación')),
                ('is_send', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_notificationemail_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transversal_notificationemail_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('notification', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='transversal.notification')),
            ],
            options={
                'verbose_name': 'Notificación Email',
                'verbose_name_plural': 'Notificaciones | Notificaciones Email',
            },
        ),
        migrations.CreateModel(
            name='NotificationMailProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('is_principal', models.BooleanField(default=False, verbose_name='¿Es principal?')),
                ('integration', models.IntegerField(choices=[(1, 'POP3'), (2, 'SMTP')], verbose_name='Integración')),
            ],
            options={
                'verbose_name': 'Proveedor de Email',
                'verbose_name_plural': 'Notificaciones | Proveedor de Email',
            },
        ),
        migrations.CreateModel(
            name='NotificationMailProviderParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('EMAIL_HOST', 'EMAIL_HOST'), ('EMAIL_PORT', 'EMAIL_PORT'), ('EMAIL_HOST_USER', 'EMAIL_HOST_USER'), ('EMAIL_HOST_PASSWORD', 'EMAIL_HOST_PASSWORD'), ('DEFAULT_FROM_EMAIL', 'DEFAULT_FROM_EMAIL'), ('SERVER_EMAIL', 'SERVER_EMAIL'), ('EMAIL_SUBJECT_PREFIX', 'EMAIL_SUBJECT_PREFIX'), ('EMAIL_USE_TLS', 'EMAIL_USE_TLS'), ('EMAIL_USE_SSL', 'EMAIL_USE_SSL')], max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.notificationmailprovider')),
            ],
            options={
                'verbose_name': 'Parámetro Email',
                'verbose_name_plural': 'Notificaciones | Parámetros Email',
            },
        ),
        migrations.CreateModel(
            name='TemplateNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('reason', models.IntegerField(choices=[(1, 'Creación de cuenta'), (2, 'Inscripción de Torneo'), (3, 'Resultado de Partido'), (4, 'Publicación de Cuadros'), (5, 'Informativos varios')], null=True, verbose_name='Motivo')),
                ('html', models.TextField(help_text='HTML El cuerpo del correo.')),
                ('mail_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transversal.notificationmailprovider', verbose_name='Email Provider')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
            },
        ),
        migrations.RemoveField(
            model_name='filetemplatenotificacion',
            name='template',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='insurer',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='modelconfig',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modelfieldconfig',
            name='model',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='destinos',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='template',
        ),
        migrations.RemoveField(
            model_name='notificacionemail',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='notificacionmailconfigproviderparam',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='notificacionpush',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='notificacionpush',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='notificacionpushconfigproviderparam',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='notificacionpushdevices',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='notificacionpushdevicesparameters',
            name='device',
        ),
        migrations.RemoveField(
            model_name='notificacionpushestado',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='notificacionpushestado',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='notificacionsms',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='notificacionsmsconfigproviderparam',
            name='provider',
        ),
        migrations.DeleteModel(
            name='SmsServiceAnswer',
        ),
        migrations.RemoveField(
            model_name='templatedocumentodinamico',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='TemplateDocumentoFijo',
        ),
        migrations.RemoveField(
            model_name='templatenotificacion',
            name='destinos',
        ),
        migrations.RemoveField(
            model_name='templatenotificacion',
            name='mail_provider',
        ),
        migrations.RemoveField(
            model_name='templatenotificacion',
            name='push_provider',
        ),
        migrations.RemoveField(
            model_name='templatenotificacion',
            name='sms_provider',
        ),
        migrations.RemoveField(
            model_name='templatenotificacion',
            name='tipo_notificacion',
        ),
        migrations.RemoveField(
            model_name='templatenotificacionparametros',
            name='template',
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'default_permissions': (), 'permissions': (('can_access_transversal', 'Puede acceder al módulo de Transversal'),)},
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='type',
            field=models.IntegerField(choices=[(1, 'Login'), (2, 'Maestro de Usuarios')], null=True, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='CategoriaTemplateDinamico',
        ),
        migrations.DeleteModel(
            name='FileTemplateNotificacion',
        ),
        migrations.DeleteModel(
            name='Insurer',
        ),
        migrations.DeleteModel(
            name='ModelConfig',
        ),
        migrations.DeleteModel(
            name='ModelFieldConfig',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='NotificacionEmail',
        ),
        migrations.DeleteModel(
            name='NotificacionMailConfigProvider',
        ),
        migrations.DeleteModel(
            name='NotificacionMailConfigProviderParam',
        ),
        migrations.DeleteModel(
            name='NotificacionPush',
        ),
        migrations.DeleteModel(
            name='NotificacionPushConfigProvider',
        ),
        migrations.DeleteModel(
            name='NotificacionPushConfigProviderParam',
        ),
        migrations.DeleteModel(
            name='NotificacionPushDevices',
        ),
        migrations.DeleteModel(
            name='NotificacionPushDevicesParameters',
        ),
        migrations.DeleteModel(
            name='NotificacionPushEstado',
        ),
        migrations.DeleteModel(
            name='NotificacionSms',
        ),
        migrations.DeleteModel(
            name='NotificacionSmsConfigProvider',
        ),
        migrations.DeleteModel(
            name='NotificacionSmsConfigProviderParam',
        ),
        migrations.DeleteModel(
            name='TemplateDocumentoDinamico',
        ),
        migrations.DeleteModel(
            name='TemplateNotificacion',
        ),
        migrations.DeleteModel(
            name='TemplateNotificacionParametros',
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transversal.templatenotification'),
        ),
    ]
